### ISSUE TITLE
panic: runtime error: index out of range [0] with length 0 under macOS

### ISSUE THREAD

**Issue by linxiaocong** [eycorsican/go-tun2socks#125]
```
sudo ./tun2socks -proxyServer 127.0.0.1:4567
Password:
2020/06/29 16:42:50 Running tun2socks

sudo route add 8.8.8.8 10.255.0.1

2020/06/29 16:43:12 new proxy connection to 8.8.8.8:53
2020/06/29 16:43:18 new proxy connection to 8.8.8.8:53
panic: runtime error: index out of range [0] with length 0

goroutine 20 [running]:
github.com/eycorsican/go-tun2socks/core.(*udpConn).WriteFrom.func1(0xc000059ee0, 0x7)
	/ext-go/1/src/github.com/eycorsican/go-tun2socks/core/udp_conn.go:140 +0x114
github.com/eycorsican/go-tun2socks/core.(*udpConn).WriteFrom(0xc0000239e0, 0xc00012e00a, 0x0, 0xffd2, 0xc00015c060, 0x0, 0x0, 0x0)
	/ext-go/1/src/github.com/eycorsican/go-tun2socks/core/udp_conn.go:140 +0xe2
github.com/eycorsican/go-tun2socks/proxy/socks.(*udpHandler).fetchUDPInput(0xc00006e440, 0x41be400, 0xc0000239e0, 0x41bef60, 0xc0000d8010)
	/ext-go/1/src/github.com/eycorsican/go-tun2socks/proxy/socks/udp.go:81 +0x261
created by github.com/eycorsican/go-tun2socks/proxy/socks.(*udpHandler).connectInternal
	/ext-go/1/src/github.com/eycorsican/go-tun2socks/proxy/socks/udp.go:152 +0x68a

./tun2socks -version
v1.16.9
```

**Comment by eycorsican** [comment]
fixed
