### ISSUE TITLE
Crash: "Error in `{proccess name}': double free or corruption"

### ISSUE THREAD

**Issue by ghostiam** [eycorsican/go-tun2socks#129]
```
goroutine 158325 [syscall]:
runtime.cgocall(0xacaf70, 0xc000d5fea0, 0xc000d5fec8)
#011/root/.go/src/runtime/cgocall.go:133 +0x5b fp=0xc000d5fe70 sp=0xc000d5fe38 pc=0x40981b
github.com/eycorsican/go-tun2socks/core._Cfunc_tcp_abort(0x7f6244007a50)
#011_cgo_gotypes.go:652 +0x41 fp=0xc000d5fea0 sp=0xc000d5fe70 pc=0xa76641
github.com/eycorsican/go-tun2socks/core.(*tcpConn).abortInternal.func1(0xc000d68a00)
#011/root/go/pkg/mod/github.com/eycorsican/go-tun2socks@v1.16.9/core/tcp_conn.go:428 +0x56 fp=0xc000d5fed8 sp=0xc000d5fea0 pc=0xa7e1d6
github.com/eycorsican/go-tun2socks/core.(*tcpConn).abortInternal(0xc000d68a00)
#011/root/go/pkg/mod/github.com/eycorsican/go-tun2socks@v1.16.9/core/tcp_conn.go:428 +0x39 fp=0xc000d5fef0 sp=0xc000d5fed8 pc=0xa7b3e9
github.com/eycorsican/go-tun2socks/core.(*tcpConn).checkAborting(0xc000d68a00, 0x0, 0x0)
#011/root/go/pkg/mod/github.com/eycorsican/go-tun2socks@v1.16.9/core/tcp_conn.go:335 +0x77 fp=0xc000d5ff28 sp=0xc000d5fef0 pc=0xa7ad47
github.com/eycorsican/go-tun2socks/core.(*tcpConn).checkState(0xc000d68a00, 0xc0008e91f8, 0xc0008e91f0)
#011/root/go/pkg/mod/github.com/eycorsican/go-tun2socks@v1.16.9/core/tcp_conn.go:358 +0x65 fp=0xc000d5ff50 sp=0xc000d5ff28 pc=0xa7af05
github.com/eycorsican/go-tun2socks/core.(*tcpConn).Abort(0xc000d68a00)
#011/root/go/pkg/mod/github.com/eycorsican/go-tun2socks@v1.16.9/core/tcp_conn.go:437 +0x71 fp=0xc000d5ff78 sp=0xc000d5ff50 pc=0xa7b471
github.com/eycorsican/go-tun2socks/core.newTCPConn.func2(0xd6da00, 0xc00029c340, 0xc000d68a00, 0x7f6244007a50)
#011/root/go/pkg/mod/github.com/eycorsican/go-tun2socks@v1.16.9/core/tcp_conn.go:114 +0x168 fp=0xc000d5ffc0 sp=0xc000d5ff78 pc=0xa7dc48
runtime.goexit()
#011/root/.go/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc000d5ffc8 sp=0xc000d5ffc0 pc=0x46d2e1
created by github.com/eycorsican/go-tun2socks/core.newTCPConn
#011/root/go/pkg/mod/github.com/eycorsican/go-tun2socks@v1.16.9/core/tcp_conn.go:111 +0x4b8
```

**Comment by eycorsican** [comment]
Assume fixed.
